#pragma once

#include <glm\glm.hpp>
#include <pb\GameObject.h>


class ProjectBlah;

namespace pb
{
	class Material;
	class VertexObjectData;

	class Renderable : virtual public GameObject
	{
	protected:

		/** @brief Override to set data for mesh.
		* A cube will be generated by default.
		**/
		virtual void SetVertexObjectData();


		/** @brief Sets object to render with desired material.**/
		void SetMaterial(Material& material);





	public:


		Renderable(const char* name = "renderable");

		~Renderable();

		void Draw();

	private:


		unsigned int* index_data_;

		unsigned int vao_;


		VertexObjectData* vo_data_;

		Material* material_ = nullptr;

	};





}