#pragma once

#include <glm\glm.hpp>
#include <pb\GameObject.h>


class ProjectBlah;

namespace pb
{
	class Material;
	class VertexObjectData;

	class Renderable : virtual public GameObject
	{

		friend class Material;

	protected:

		/** @brief Override to set data for mesh.
		* A cube will be generated by default.
		**/
		virtual void SetVertexObjectData();


		/** @brief Sets object to render with desired material.**/
		void SetMaterial(Material& material);





	public:


		Renderable(const char* name = "renderable");

		~Renderable();

		void Draw();

	private:

		Material* material_ = nullptr;



		glm::mat4 model_view_projection_;
		unsigned int model_view_projection_id_;


		unsigned int* index_data_;
		unsigned int index_data_count_;
		unsigned int index_buffer_;

		glm::vec4* position_data_;
		unsigned int position_data_count_;
		unsigned int position_buffer_;

	

		/// @todo Put the rest of the possible vertex info here



	};





}